apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: l29f6yyst-go 
  janus-idp.io/tekton: l29f6yyst-go
  backstage.io/kubernetes-id: l29f6yyst-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: l29f6yyst-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml